// <auto-generated />
using ECommerceLabWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECommerceLabWebApp.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20200427023329_Seeding")]
    partial class Seeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ECommerceLabWebApp.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Description of Widget",
                            ImageUrl = "",
                            Name = "Widget",
                            Price = 30m,
                            SKU = "12345"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Description of Sprocket",
                            ImageUrl = "",
                            Name = "Sprocket",
                            Price = 45m,
                            SKU = "23456"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Description of Thingamabob",
                            ImageUrl = "",
                            Name = "Thingamabob",
                            Price = 15m,
                            SKU = "34567"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Description of Gizmo",
                            ImageUrl = "",
                            Name = "Gizmo",
                            Price = 200m,
                            SKU = "45678"
                        },
                        new
                        {
                            ID = 5,
                            Description = "Description of Gadget",
                            ImageUrl = "",
                            Name = "Gadget",
                            Price = 70m,
                            SKU = "56789"
                        },
                        new
                        {
                            ID = 6,
                            Description = "Description of Device",
                            ImageUrl = "",
                            Name = "Device",
                            Price = 90m,
                            SKU = "67890"
                        },
                        new
                        {
                            ID = 7,
                            Description = "Description of Doohickey",
                            ImageUrl = "",
                            Name = "Doohickey",
                            Price = 5m,
                            SKU = "78901"
                        },
                        new
                        {
                            ID = 8,
                            Description = "Description of Rube Goldberg Machine",
                            ImageUrl = "",
                            Name = "Rube Goldberg Machine",
                            Price = 42m,
                            SKU = "89012"
                        },
                        new
                        {
                            ID = 9,
                            Description = "Description of Contraption",
                            ImageUrl = "",
                            Name = "Contraption",
                            Price = 100m,
                            SKU = "90123"
                        },
                        new
                        {
                            ID = 10,
                            Description = "Description of Whatchamacallit",
                            ImageUrl = "",
                            Name = "Whatchamacallit",
                            Price = 0m,
                            SKU = "01234"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
